name: 'Invoke terraform Vars API'
description: 'Build Json and Invoke API to set Terraform Workspace variable'
inputs:
  attributes:  
    description: 'array of attributes'
    required: true
  workSpaceName:
    description: 'Terraform workspace name'
    required: true
  organizationName:
    description: 'Terraform organization Name'
    required: true
outputs:
  output: 
    description: 'Output'
runs:
  using: 'node12'
  main: 'index.js'